pspsdk-1.0+beta2: tools/bin2s.c File Reference
bin2s.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
Functions
int main (int argc, char *argv[])
Variables
unsigned char * buffer
Function Documentation
int main (int argc, char * argv[])
References buffer, fclose(), fopen(), fprintf(), fread(), fseek(), ftell(), i, malloc(), NULL, printf(), SEEK_END, and SEEK_SET.
Variable Documentation
unsigned char* buffer