pspsdk-1.0+beta2: tools/bin2o.c File Reference
bin2o.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct elf_section_t
struct elf_symbol_t
Typedefs
typedef unsigned char u8
typedef unsigned short u16
typedef unsigned int u32
Functions
u32 LE32 (u32 b)
u16 LE16 (u16 b)
void create_elf (FILE *dest, const unsigned char *source, u32 size, const char *label)
void usage ()
int main (int argc, char *argv[])
Variables
int alignment = 16
int have_size = 1
int have_irx = 0
unsigned char elf_header []
char shstrtab [] = "\0.shstrtab\0.symtab\0.strtab\0.data"
Typedef Documentation
typedef unsigned short u16
typedef unsigned int u32
typedef unsigned char u8
Function Documentation
void create_elf (FILE * dest, const unsigned char * source, u32 size, const char * label)
References alignment, data_size, elf_header, fputc(), fwrite(), have_irx, have_size, i, LE16(), LE32(), elf_section_t::sh_addr, elf_section_t::sh_addralign, elf_section_t::sh_entsize, elf_section_t::sh_flags, elf_section_t::sh_info, elf_section_t::sh_link, elf_section_t::sh_name, elf_section_t::sh_offset, elf_section_t::sh_size, elf_section_t::sh_type, shstrtab, elf_symbol_t::st_info, elf_symbol_t::st_name, elf_symbol_t::st_other, elf_symbol_t::st_shndx, elf_symbol_t::st_size, elf_symbol_t::st_value, strcat(), strcpy(), and strlen().
Referenced by main().
u16 LE16 (u16 b)
References b.
Referenced by create_elf().
u32 LE32 (u32 b)
References b.
Referenced by create_elf().
int main (int argc, char * argv[])
References alignment, buffer, create_elf(), fclose(), fopen(), fread(), free(), fseek(), ftell(), have_irx, have_size, i, malloc(), NULL, printf(), SEEK_END, SEEK_SET, size, and usage().
void usage ()
References printf().
Referenced by main().
Variable Documentation
int alignment = 16
Referenced by create_elf(), and main().
unsigned char elf_header[]
Initial value:
 {
    0x7f,  'E',  'L',  'F', 0x01, 0x01, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x00,
    0x08, 0x00,
    0x01, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x34, 0x00, 0x00, 0x00,
    0x01, 0x40, 0x92, 0x20,
    0x34, 0x00,
    0x00, 0x00,
    0x00, 0x00,
    0x28, 0x00,
    0x05, 0x00,
    0x01, 0x00,
}
Referenced by create_elf().
int have_irx = 0
Referenced by create_elf(), and main().
int have_size = 1
Referenced by create_elf(), and main().
char shstrtab[] = "\0.shstrtab\0.symtab\0.strtab\0.data"
Referenced by create_elf().