pspsdk-1.0+beta2: src/libc/ctype.h File Reference
ctype.h File Reference
Functions
int isalnum (int)
int isalpha (int)
int iscntrl (int)
int isdigit (int)
int isgraph (int)
int islower (int)
int isprint (int)
int ispunct (int)
int isspace (int)
int isupper (int)
int isxdigit (int)
int tolower (int)
int toupper (int)
Function Documentation
int isalnum (int)
Referenced by parse_string().
int isalpha (int)
int iscntrl (int)
int isdigit (int)
int isgraph (int)
int islower (int)
int isprint (int)
int ispunct (int)
int isspace (int)
Referenced by strip_whitespace(), and strip_wsp().
int isupper (int)
int isxdigit (int)
Referenced by validate_number().
int tolower (int)
int toupper (int)