pspsdk-1.0+beta2: tools/getopt.h File Reference
getopt.h File Reference
#include <unistd.h>
Data Structures
struct option
Defines
#define no_argument 0
#define required_argument 1
#define optional_argument 2
Functions
int getopt_long (int, char *const *, const char *, const struct option *, int *)
Variables
char * optarg
int optind
int opterr
int optopt
Define Documentation
#define no_argument 0
Referenced by getopt_long().
#define optional_argument 2
Referenced by getopt_long().
#define required_argument 1
Referenced by getopt_long().
Function Documentation
int getopt_long (int , char *const * , const char * , const struct option * , int *)
References BADARG, BADCH, EMSG, option::flag, fprintf(), i, name, option::name, no_argument, NULL, optarg, optind, optional_argument, optopt, PRINT_ERROR, required_argument, stderr, strchr(), strlen(), strncmp(), and option::val.
Referenced by process_args().
Variable Documentation
char* optarg
Referenced by getopt_long(), and process_args().
int opterr
int optind
Referenced by getopt_long(), and process_args().
int optopt
Referenced by getopt_long().