pspsdk-1.0+beta2: src/libc/init.c File Reference
init.c File Reference
Functions
void _pspsdk_alloc_init ()
void _pspsdk_alloc_deinit ()
void _pspsdk_stdio_init ()
void _pspsdk_stdio_deinit ()
void _pspsdk_stdlib_init ()
void _pspsdk_stdlib_deinit ()
__attribute__ ((weak, constructor))
__attribute__ ((weak, destructor))
Function Documentation
__attribute__ ((weak, constructor))
References _pspsdk_alloc_init(), _pspsdk_stdio_init(), and _pspsdk_stdlib_init().
__attribute__ ((weak, destructor))
References _pspsdk_alloc_deinit(), _pspsdk_stdio_deinit(), and _pspsdk_stdlib_deinit().
void _pspsdk_alloc_deinit ()
void _pspsdk_alloc_init ()
void _pspsdk_stdio_deinit ()
Referenced by __attribute__().
void _pspsdk_stdio_init ()
Referenced by __attribute__().
void _pspsdk_stdlib_deinit ()
Referenced by __attribute__().
void _pspsdk_stdlib_init ()
Referenced by __attribute__().