pspsdk-1.0+beta2: src/libc/malloc.h File Reference
malloc.h File Reference
#include <pspkernel.h>
#include <stddef.h>
#include <stdarg.h>
Functions
void * malloc (size_t size)
void * realloc (void *ptr, size_t size)
void * calloc (size_t n, size_t size)
void * memalign (size_t align, size_t size)
void free (void *ptr)
void * __mem_walk_begin (void)
void __mem_walk_read (void *token, u32 *size, void **ptr, int *valid)
void * __mem_walk_inc (void *token)
int __mem_walk_end (void *token)
Function Documentation
void* __mem_walk_begin (void)
int __mem_walk_end (void * token)
void* __mem_walk_inc (void * token)
void __mem_walk_read (void * token, u32 * size, void ** ptr, int * valid)
void* calloc (size_t n, size_t size)
void free (void * ptr)
Referenced by __attribute__(), find_pspdev_path(), free_alias_chain(), free_data(), free_export_chain(), free_lib_data(), main(), output_prx(), pspvfpu_deletecontext(), and remove_weak_relocs().
void* malloc (size_t size)
Referenced by find_pspdev_path(), internal_do_export(), load_file(), load_mapfile(), load_sections(), main(), output_prx(), psp_export_alias(), psp_export_start(), and remove_weak_relocs().
void* memalign (size_t align, size_t size)
Referenced by pspvfpu_initcontext().
void* realloc (void * ptr, size_t size)