pspsdk-1.0+beta2: tools/pack-pbp.c File Reference
pack-pbp.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Functions
int main (int argc, char *argv[])
Variables
struct {
char signature [4]
char version [4]
int offset [8]
} header
int maxbuffer = 16 * 1024 * 1024
Function Documentation
int main (int argc, char * argv[])
References buffer, fclose(), fopen(), fread(), free(), fseek(), ftell(), fwrite(), header, malloc(), maxbuffer, NULL, printf(), SEEK_END, SEEK_SET, and strncmp().
Variable Documentation
struct { ... } header
Referenced by main().
int maxbuffer = 16 * 1024 * 1024
Referenced by main().
int offset[8]
Referenced by sceGuBoneMatrix(), sceGuDepthOffset(), and sceGuTexLevelMode().
char signature[4]
char version[4]