pspsdk-1.0+beta2: tools/psp-build-exports.c File Reference
psp-build-exports.c File Reference
#include <stdio.h>
#include <getopt.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>
#include <ctype.h>
#include "sha1.h"
Data Structures
struct psp_export
struct psp_alias
struct psp_lib
struct export_cmd
Defines
#define MAX_LIB_NAME 27
#define MAX_LIB_FUNCS 65535
#define MAX_LIB_VARS 255
#define MAX_LIB_ENTRY_NAME 127
#define MAX_ERROR 1024
#define MAX_LINE 1024
#define SYSTEM_LIB_NAME "syslib"
Enumerations
enum PspConfigMode {
PSP_BUILD_UNKNOWN, PSP_BUILD_EXPORTS, PSP_BUILD_STUBS, PSP_BUILD_STUBS_NEW,
PSP_CONFIG_UNKNOWN, PSP_CONFIG_PSPSDK_PATH, PSP_CONFIG_PSPDEV_PATH, PSP_CONFIG_PSP_PREFIX
}
Functions
void free_export_chain (struct psp_export *pHead)
void free_alias_chain (struct psp_alias *pHead)
void free_lib_data (void)
const char * find_alias (struct psp_alias *pHead, const char *name)
int process_args (int argc, char **argv)
void print_help (void)
void strip_whitespace (char *dest, const char *src)
int parse_string (char *line, char **params, int max_params)
void build_exports_output_extern (struct psp_export *pHead)
void build_exports_output_nids (struct psp_export *pHead)
void build_exports_output_names (struct psp_export *pHead)
void build_exports (void)
void build_stubs_output_lib (struct psp_lib *pLib)
void build_stubs_output_lib_new (struct psp_lib *pLib)
void build_stubs (void)
int validate_number (const char *str, unsigned int *num)
int psp_begin_exports (char **params)
int psp_end_exports (char **params)
int psp_export_start (char **params)
int psp_export_end (char **params)
int internal_do_export (const char *name, unsigned int nid, struct psp_export **pHead)
int psp_export_func_nid (char **params)
int psp_export_func_hash (char **params)
int psp_export_var_nid (char **params)
int psp_export_var_hash (char **params)
int psp_export_alias (char **params)
int process_command (const char *cmd, char **params, int param_count)
int load_exports (void)
void dump_exports (void)
int main (int argc, char **argv)
Variables
struct export_cmd commands []
Define Documentation
#define MAX_ERROR 1024
Referenced by internal_do_export(), parse_string(), process_command(), psp_export_alias(), psp_export_end(), psp_export_func_hash(), psp_export_func_nid(), psp_export_start(), psp_export_var_hash(), psp_export_var_nid(), and validate_number().
#define MAX_LIB_ENTRY_NAME 127
Referenced by internal_do_export(), and psp_export_alias().
#define MAX_LIB_FUNCS 65535
Referenced by psp_export_func_hash(), and psp_export_func_nid().
#define MAX_LIB_NAME 27
Referenced by psp_export_start().
#define MAX_LIB_VARS 255
Referenced by psp_export_var_hash(), and psp_export_var_nid().
#define MAX_LINE 1024
Referenced by load_exports().
#define SYSTEM_LIB_NAME "syslib"
Referenced by build_exports(), and build_stubs().
Enumeration Type Documentation
enum PspConfigMode
Enumerator:
PSP_BUILD_UNKNOWN
PSP_BUILD_EXPORTS
PSP_BUILD_STUBS
PSP_BUILD_STUBS_NEW
PSP_CONFIG_UNKNOWN
PSP_CONFIG_PSPSDK_PATH
PSP_CONFIG_PSPDEV_PATH
PSP_CONFIG_PSP_PREFIX
Function Documentation
void build_exports (void)
References psp_lib::attr, build_exports_output_extern(), build_exports_output_names(), build_exports_output_nids(), fprintf(), psp_lib::funcCount, psp_lib::name, NULL, psp_lib::pFuncHead, psp_lib::pNext, psp_lib::pVarHead, stdout, strcmp(), SYSTEM_LIB_NAME, psp_lib::varCount, and psp_lib::ver.
Referenced by main().
void build_exports_output_extern (struct psp_export * pHead)
References fprintf(), psp_export::name, NULL, psp_export::pNext, and stdout.
Referenced by build_exports().
void build_exports_output_names (struct psp_export * pHead)
References fprintf(), psp_export::name, NULL, psp_export::pNext, and stdout.
Referenced by build_exports().
void build_exports_output_nids (struct psp_export * pHead)
References fprintf(), psp_export::nid, NULL, psp_export::pNext, and stdout.
Referenced by build_exports().
void build_stubs (void)
References build_stubs_output_lib(), build_stubs_output_lib_new(), psp_lib::name, NULL, psp_lib::pNext, PSP_BUILD_STUBS, strcmp(), and SYSTEM_LIB_NAME.
Referenced by main().
void build_stubs_output_lib (struct psp_lib * pLib)
References psp_lib::attr, fclose(), filename, find_alias(), fopen(), fp, fprintf(), psp_lib::funcCount, psp_export::name, psp_lib::name, psp_export::nid, NULL, psp_lib::pAliasHead, psp_lib::pFuncHead, psp_export::pNext, snprintf(), stderr, and psp_lib::ver.
Referenced by build_stubs().
void build_stubs_output_lib_new (struct psp_lib * pLib)
References psp_lib::attr, fclose(), filename, find_alias(), fopen(), fp, fprintf(), i, psp_export::name, psp_lib::name, psp_export::nid, NULL, psp_lib::pAliasHead, psp_lib::pFuncHead, psp_export::pNext, snprintf(), stderr, and psp_lib::ver.
Referenced by build_stubs().
void dump_exports (void)
References psp_lib::attr, count, fprintf(), psp_lib::funcCount, psp_export::name, psp_lib::name, psp_export::nid, NULL, psp_lib::pFuncHead, psp_lib::pNext, psp_export::pNext, psp_lib::pVarHead, stderr, psp_lib::varCount, and psp_lib::ver.
Referenced by main().
const char* find_alias (struct psp_alias * pHead, const char * name)
References psp_alias::alias, psp_alias::name, NULL, psp_alias::pNext, and strcmp().
Referenced by build_stubs_output_lib(), and build_stubs_output_lib_new().
void free_alias_chain (struct psp_alias * pHead)
References free(), NULL, and psp_alias::pNext.
Referenced by free_lib_data().
void free_export_chain (struct psp_export * pHead)
References free(), NULL, and psp_export::pNext.
Referenced by free_lib_data().
void free_lib_data (void)
References free(), free_alias_chain(), free_export_chain(), NULL, psp_lib::pAliasHead, psp_lib::pFuncHead, psp_lib::pNext, and psp_lib::pVarHead.
Referenced by main().
int internal_do_export (const char * name, unsigned int nid, struct psp_export ** pHead)
References assert, malloc(), MAX_ERROR, MAX_LIB_ENTRY_NAME, memset(), psp_export::name, psp_export::nid, NULL, psp_export::pNext, snprintf(), and strncpy().
Referenced by psp_export_func_hash(), psp_export_func_nid(), psp_export_var_hash(), and psp_export_var_nid().
int load_exports (void)
References fgets(), fopen(), fp, fprintf(), i, MAX_LINE, NULL, export_cmd::params, parse_string(), process_command(), stderr, and strip_whitespace().
Referenced by main().
int main (int argc, char ** argv)
References build_exports(), build_stubs(), dump_exports(), free_lib_data(), load_exports(), print_help(), process_args(), PSP_BUILD_EXPORTS, PSP_BUILD_STUBS, and PSP_BUILD_STUBS_NEW.
int parse_string (char * line, char ** params, int max_params)
References assert, isalnum(), MAX_ERROR, NULL, snprintf(), and strtok().
Referenced by load_exports().
void print_help (void)
References fprintf(), and stderr.
Referenced by main().
int process_args (int argc, char ** argv)
References ch, getopt_long(), NULL, optind, PSP_BUILD_EXPORTS, PSP_BUILD_STUBS, PSP_BUILD_STUBS_NEW, and PSP_BUILD_UNKNOWN.
int process_command (const char * cmd, char ** params, int param_count)
References assert, export_cmd::handler, i, MAX_ERROR, name, NULL, snprintf(), and strcmp().
Referenced by load_exports().
int psp_begin_exports (char ** params)
int psp_end_exports (char ** params)
References NULL.
int psp_export_alias (char ** params)
References psp_alias::alias, fprintf(), malloc(), MAX_ERROR, MAX_LIB_ENTRY_NAME, memset(), psp_alias::name, NULL, psp_lib::pAliasHead, psp_alias::pNext, snprintf(), stderr, and strncpy().
int psp_export_end (char ** params)
References MAX_ERROR, NULL, psp_lib::pNext, and snprintf().
int psp_export_func_hash (char ** params)
References psp_lib::funcCount, internal_do_export(), MAX_ERROR, MAX_LIB_FUNCS, psp_export::nid, NULL, psp_lib::pFuncHead, sha1(), SHA1_DIGEST_SIZE, snprintf(), and strlen().
int psp_export_func_nid (char ** params)
References psp_lib::funcCount, internal_do_export(), MAX_ERROR, MAX_LIB_FUNCS, psp_export::nid, NULL, psp_lib::pFuncHead, snprintf(), and validate_number().
int psp_export_start (char ** params)
References psp_lib::attr, attr, malloc(), MAX_ERROR, MAX_LIB_NAME, memset(), psp_lib::name, NULL, snprintf(), strncpy(), validate_number(), and psp_lib::ver.
int psp_export_var_hash (char ** params)
References internal_do_export(), MAX_ERROR, MAX_LIB_VARS, psp_export::nid, NULL, psp_lib::pVarHead, sha1(), SHA1_DIGEST_SIZE, snprintf(), strlen(), and psp_lib::varCount.
int psp_export_var_nid (char ** params)
References internal_do_export(), MAX_ERROR, MAX_LIB_VARS, psp_export::nid, NULL, psp_lib::pVarHead, snprintf(), validate_number(), and psp_lib::varCount.
void strip_whitespace (char * dest, const char * src)
References assert, isspace(), and NULL.
Referenced by load_exports().
int validate_number (const char * str, unsigned int * num)
References assert, endp, isxdigit(), MAX_ERROR, NULL, snprintf(), and strtoul().
Referenced by psp_export_func_nid(), psp_export_start(), and psp_export_var_nid().
Variable Documentation
struct export_cmd commands[]
Initial value:
{
        { "PSP_BEGIN_EXPORTS", 0, psp_begin_exports },
        { "PSP_END_EXPORTS", 0, psp_end_exports },
        { "PSP_EXPORT_START", 3, psp_export_start },
        { "PSP_EXPORT_END", 0, psp_export_end },
        { "PSP_EXPORT_FUNC_NID", 2, psp_export_func_nid },
        { "PSP_EXPORT_FUNC_HASH", 1, psp_export_func_hash },
        { "PSP_EXPORT_FUNC", 1, psp_export_func_hash },
        { "PSP_EXPORT_VAR_NID", 2, psp_export_var_nid },
        { "PSP_EXPORT_VAR", 1, psp_export_var_hash },
        { "PSP_EXPORT_VAR_HASH", 1, psp_export_var_hash },
        { "PSP_EXPORT_ALIAS", 2, psp_export_alias },
        { NULL, 0, NULL }
}