pspsdk-1.0+beta2: tools/psp-config.c File Reference
psp-config.c File Reference
#include <stdio.h>
#include <getopt.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
Defines
#define PSPDEV_ENV "PSPDEV"
#define PATH_ENV "PATH"
#define MAX_PATH 256
#define PATH_SEP ":"
#define DIR_SEP '/'
#define DIR_SEP_STR "/"
#define PSPDEV_PATH_SUFFIX "/bin/psp-config"
Enumerations
enum PspConfigMode {
PSP_BUILD_UNKNOWN, PSP_BUILD_EXPORTS, PSP_BUILD_STUBS, PSP_BUILD_STUBS_NEW,
PSP_CONFIG_UNKNOWN, PSP_CONFIG_PSPSDK_PATH, PSP_CONFIG_PSPDEV_PATH, PSP_CONFIG_PSP_PREFIX
}
Functions
int process_args (int argc, char **argv)
void print_help (void)
void normalize_path (char *out)
char * find_pspdev_path (char *name)
void print_path (char *name)
int main (int argc, char **argv)
Define Documentation
#define DIR_SEP '/'
Referenced by find_pspdev_path(), and print_path().
#define DIR_SEP_STR "/"
Referenced by find_pspdev_path().
#define MAX_PATH 256
Referenced by find_pspdev_path(), and main().
#define PATH_ENV "PATH"
Referenced by find_pspdev_path().
#define PATH_SEP ":"
Referenced by find_pspdev_path().
#define PSPDEV_ENV "PSPDEV"
Referenced by print_path().
#define PSPDEV_PATH_SUFFIX "/bin/psp-config"
Referenced by find_pspdev_path().
Enumeration Type Documentation
enum PspConfigMode
Enumerator:
PSP_BUILD_UNKNOWN
PSP_BUILD_EXPORTS
PSP_BUILD_STUBS
PSP_BUILD_STUBS_NEW
PSP_CONFIG_UNKNOWN
PSP_CONFIG_PSPSDK_PATH
PSP_CONFIG_PSPDEV_PATH
PSP_CONFIG_PSP_PREFIX
Function Documentation
char* find_pspdev_path (char * name)
References DIR_SEP, DIR_SEP_STR, fprintf(), free(), getenv(), malloc(), MAX_PATH, normalize_path(), NULL, PATH_ENV, PATH_SEP, PSPDEV_PATH_SUFFIX, stderr, strcat(), strchr(), strcmp(), strcpy(), strlen(), strncat(), strncpy(), and strtok().
Referenced by print_path().
int main (int argc, char ** argv)
References MAX_PATH, print_help(), print_path(), process_args(), and strcpy().
void normalize_path (char * out)
References i.
Referenced by find_pspdev_path().
void print_help (void)
References fprintf(), and stderr.
void print_path (char * name)
References DIR_SEP, find_pspdev_path(), fprintf(), getenv(), NULL, printf(), PSP_CONFIG_PSP_PREFIX, PSP_CONFIG_PSPDEV_PATH, PSP_CONFIG_PSPSDK_PATH, PSPDEV_ENV, and stderr.
Referenced by main().
int process_args (int argc, char ** argv)
References ch, fprintf(), getopt_long(), NULL, PSP_CONFIG_PSP_PREFIX, PSP_CONFIG_PSPDEV_PATH, PSP_CONFIG_PSPSDK_PATH, PSP_CONFIG_UNKNOWN, and stderr.