pspsdk-1.0+beta2: src/vfpu/pspvfpu.h File Reference
pspvfpu.h File Reference
Defines
#define VMAT0 (1<<0)
#define VMAT1 (1<<1)
#define VMAT2 (1<<2)
#define VMAT3 (1<<3)
#define VMAT4 (1<<4)
#define VMAT5 (1<<5)
#define VMAT6 (1<<6)
#define VMAT7 (1<<7)
#define VFPU_ALIGNMENT (sizeof(float) * 4)
Typedefs
typedef unsigned char vfpumatrixset_t
Functions
struct pspvfpu_context * pspvfpu_initcontext (void)
Prepare to use the VFPU.
void pspvfpu_deletecontext (struct pspvfpu_context *context)
Delete a VFPU context.
void pspvfpu_use_matrices (struct pspvfpu_context *context, vfpumatrixset_t keepset, vfpumatrixset_t tempset)
Use a set of VFPU matrices.
Define Documentation
#define VFPU_ALIGNMENT (sizeof(float) * 4)
Referenced by pspvfpu_initcontext().
#define VMAT0 (1<<0)
#define VMAT1 (1<<1)
#define VMAT2 (1<<2)
#define VMAT3 (1<<3)
#define VMAT4 (1<<4)
#define VMAT5 (1<<5)
#define VMAT6 (1<<6)
#define VMAT7 (1<<7)
Typedef Documentation
typedef unsigned char vfpumatrixset_t
Function Documentation
void pspvfpu_deletecontext (struct pspvfpu_context * context)
Delete a VFPU context.
This frees the resources used by the VFPU context.
Parameters:
context The VFPU context to be deleted.
References free(), i, NMAT, and NULL.
struct pspvfpu_context* pspvfpu_initcontext (void) [read]
Prepare to use the VFPU.
This set's the calling thread's VFPU attribute, and returns a pointer to some VFPU state storage. The initial value all all VFPU matrix registers is undefined.
Returns:
A VFPU context
References c, memalign(), NULL, pspvfpu_context::owned, PSP_THREAD_ATTR_VFPU, sceKernelChangeCurrentThreadAttr(), pspvfpu_context::valid, and VFPU_ALIGNMENT.
void pspvfpu_use_matrices (struct pspvfpu_context * context, vfpumatrixset_t keepset, vfpumatrixset_t tempset)
Use a set of VFPU matrices.
This restores the parts of the VFPU state the caller wants restored (if necessary). If the caller was the previous user of the the matrix set, then this call is effectively a no-op. If a matrix has never been used by this context before, then it will initially have an undefined value.
Parameters:
context The VFPU context the caller wants to restore from. It is valid to pass NULL as a context. This means the caller wants to reserve a temporary matrix without affecting other VFPU users, but doesn't want any long-term matrices itself.
keepset The set of matrices the caller wants to use, and keep the values persistently.
tempset A set of matrices the callers wants to use temporarily, but doesn't care about the values in the long-term.
References c, NULL, pspvfpu_context::owned, and pspvfpu_context::valid.