pspsdk-1.0+beta2: tools/sha1.h File Reference
sha1.h File Reference
#include <limits.h>
Data Structures
struct sha1_ctx
Defines
#define SHA1_BLOCK_SIZE 64
#define SHA1_DIGEST_SIZE 20
Functions
void sha1_compile (sha1_ctx ctx[1])
void sha1_begin (sha1_ctx ctx[1])
void sha1_hash (const unsigned char data[], unsigned long len, sha1_ctx ctx[1])
void sha1_end (unsigned char hval[], sha1_ctx ctx[1])
void sha1 (unsigned char hval[], const unsigned char data[], unsigned long len)
Define Documentation
#define SHA1_BLOCK_SIZE 64
Referenced by sha1_end(), and sha1_hash().
#define SHA1_DIGEST_SIZE 20
Referenced by load_mapfile(), psp_export_func_hash(), psp_export_var_hash(), and sha1_end().
Function Documentation
void sha1 (unsigned char hval[], const unsigned char data[], unsigned long len)
References sha1_begin(), sha1_end(), and sha1_hash().
Referenced by load_mapfile(), psp_export_func_hash(), and psp_export_var_hash().
void sha1_begin (sha1_ctx ctx[1])
References sha1_ctx::count, and sha1_ctx::hash.
Referenced by sha1().
void sha1_compile (sha1_ctx ctx[1])
References ch, five_cycle, sha1_ctx::hash, hf, maj, memcpy(), one_cycle, parity, v0, v1, w, and sha1_ctx::wbuf.
Referenced by sha1_end(), and sha1_hash().
void sha1_end (unsigned char hval[], sha1_ctx ctx[1])
References bsw_32, sha1_ctx::count, sha1_ctx::hash, i, SHA1_BLOCK_SIZE, sha1_compile(), SHA1_DIGEST_SIZE, SHA1_MASK, and sha1_ctx::wbuf.
Referenced by sha1().
void sha1_hash (const unsigned char data[], unsigned long len, sha1_ctx ctx[1])
References bsw_32, sha1_ctx::count, memcpy(), SHA1_BLOCK_SIZE, sha1_compile(), SHA1_MASK, sp, and sha1_ctx::wbuf.
Referenced by sha1().