pspsdk-1.0+beta2: src/libc/stdio.h File Reference
stdio.h File Reference
#include <pspkernel.h>
#include <stdarg.h>
#include <sys/types.h>
Data Structures
struct FILE
Defines
#define STDIN_FILENO 0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2
#define _open open
#define _close close
#define _read read
#define _write write
#define _lseek lseek
#define _O_APPEND O_APPEND
#define _O_BINARY O_BINARY
#define _O_CREAT O_CREAT
#define _O_RDONKY O_RDONKY
#define _O_RDWR O_RDWR
#define _O_TEXT O_TEXT
#define _O_TRUNC O_TRUNC
#define _O_WRONLY O_WRONLY
#define O_BINARY 0
#define O_TEXT 0
#define BUFSIZ 1024
#define _NFILE 16
#define _IOFBF 0x0000
#define _IOLBF 0x0100
#define _IONBF 0x0004
#define _IOEOF 0x0020
#define _IOERR 0x0040
#define _IOREAD 0x0001
#define _IOWRT 0x0002
#define _IORW 0x0200
#define _IOMYBUF 0x0010
#define EOF (-1)
#define FOPEN_MAX _NFILE
#define FILENAME_MAX 1024
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define __FPOS_T_DEFINED
#define __FILE_DEFINED
#define stdin (&__iob[0])
#define stdout (&__iob[1])
#define stderr (&__iob[2])
Typedefs
typedef long fpos_t
Functions
void clearerr (FILE *)
int feof (FILE *)
int ferror (FILE *)
FILE * fopen (const char *, const char *)
FILE * fopen64 (const char *, const char *)
FILE * fdopen (int, const char *)
int fclose (FILE *)
int fflush (FILE *)
int fgetc (FILE *)
int fgetpos (FILE *, fpos_t *)
int fgetpos64 (FILE *, int64_t *)
char * fgets (char *, int, FILE *)
int fileno (FILE *)
int fputc (int, FILE *)
int fputs (const char *, FILE *)
size_t fread (void *, size_t, size_t, FILE *)
FILE * freopen (const char *, const char *, FILE *)
int fscanf (FILE *, const char *,...)
int fseek (FILE *, long, int)
int fseeko64 (FILE *, int64_t, int)
int fsetpos (FILE *, const fpos_t *)
long ftell (FILE *)
int64_t ftello64 (FILE *)
size_t fwrite (const void *, size_t, size_t, FILE *)
int getc (FILE *)
int getchar (void)
char * gets (char *)
void perror (const char *)
int putc (int, FILE *)
int puts (const char *)
int remove (const char *)
int rename (const char *, const char *)
void rewind (FILE *)
int scanf (const char *,...)
int setbuf (FILE *, char *)
int setvbuf (FILE *, char *, int, size_t)
int sscanf (const char *, const char *,...)
FILE * tmpfile (void)
char * tmpnam (char *)
int vfscanf (FILE *, const char *, va_list)
int vscanf (const char *, va_list)
int vsscanf (const char *, const char *, va_list)
int vxscanf (int(*xgetc)(void **), void(*xungetc)(int, void **), void *stream, const char *, va_list)
int xscanf (int(*xgetc)(void **), void(*xungetc)(int, void **), void *stream, const char *,...)
int ungetc (int, FILE *)
int _fcloseall (void)
int _fflushall (void)
int chdir (const char *path)
int vxprintf (void(*func)(char *, int, void *), void *arg, const char *format, va_list ap)
int vsnprintf (char *buf, size_t n, const char *fmt, va_list ap)
int vsprintf (char *buf, const char *fmt, va_list ap)
char * vmprintf (const char *zFormat, va_list ap)
int vfprintf (FILE *pOut, const char *zFormat, va_list ap)
int vprintf (const char *format, va_list ap)
int vasprintf (char **strp, const char *format, va_list ap)
int xprintf (void(*func)(char *, int, void *), void *arg, const char *format,...) __attribute__((format(printf
int int snprintf (char *str, size_t sz, const char *format,...) __attribute__((format(printf
int int int sprintf (char *buf, const char *fmt,...) __attribute__((format(printf
int int int char * mprintf (const char *zFormat,...) __attribute__((format(printf
int int int char int fprintf (FILE *pOut, const char *zFormat,...) __attribute__((format(printf
int int int char int int printf (const char *format,...) __attribute__((format(printf
int int int char int int int asprintf (char **strp, const char *format,...) __attribute__((format(printf
int int int char int int int int putchar (int)
int npmPuts (const char *buf)
int nprintf (const char *format,...)
int vnprintf (const char *format, va_list args)
int sio_printf (const char *format,...)
Variables
FILE __iob [_NFILE]
Define Documentation
#define __FILE_DEFINED
#define __FPOS_T_DEFINED
#define _close close
#define _IOEOF 0x0020
#define _IOERR 0x0040
#define _IOFBF 0x0000
#define _IOLBF 0x0100
#define _IOMYBUF 0x0010
#define _IONBF 0x0004
#define _IOREAD 0x0001
#define _IORW 0x0200
#define _IOWRT 0x0002
#define _lseek lseek
#define _NFILE 16
#define _O_APPEND O_APPEND
#define _O_BINARY O_BINARY
#define _O_CREAT O_CREAT
#define _O_RDONKY O_RDONKY
#define _O_RDWR O_RDWR
#define _O_TEXT O_TEXT
#define _O_TRUNC O_TRUNC
#define _O_WRONLY O_WRONLY
#define _open open
#define _read read
#define _write write
#define BUFSIZ 1024
#define EOF (-1)
#define FILENAME_MAX 1024
#define FOPEN_MAX _NFILE
#define O_BINARY 0
#define O_TEXT 0
#define SEEK_CUR 1
#define SEEK_END 2
Referenced by load_file(), and main().
#define SEEK_SET 0
Referenced by main().
#define stderr (&__iob[2])
Referenced by add_dword(), add_string(), build_stubs_output_lib(), build_stubs_output_lib_new(), calculate_outsize(), dump_exports(), find_pspdev_path(), fixup_imports(), fixup_nidmap(), getopt_long(), load_exports(), load_file(), load_mapfile(), load_sections(), main(), output_prx(), output_shstrtab(), print_help(), print_path(), process_args(), process_relocs(), psp_export_alias(), remove_weak_relocs(), and validate_header().
#define STDERR_FILENO 2
#define stdin (&__iob[0])
#define STDIN_FILENO 0
#define stdout (&__iob[1])
Referenced by build_exports(), build_exports_output_extern(), build_exports_output_names(), and build_exports_output_nids().
#define STDOUT_FILENO 1
Typedef Documentation
typedef long fpos_t
Function Documentation
int _fcloseall (void)
int _fflushall (void)
int int int char int int int asprintf (char ** strp, const char * format, ...)
int chdir (const char * path)
void clearerr (FILE *)
int fclose (FILE *)
Referenced by build_stubs_output_lib(), build_stubs_output_lib_new(), gprof_cleanup(), load_file(), load_mapfile(), main(), and output_prx().
FILE* fdopen (int , const char *)
int feof (FILE *)
int ferror (FILE *)
int fflush (FILE *)
int fgetc (FILE *)
int fgetpos (FILE * , fpos_t *)
int fgetpos64 (FILE * , int64_t *)
char* fgets (char * , int , FILE *)
Referenced by load_exports(), and load_mapfile().
int fileno (FILE *)
FILE* fopen (const char * , const char *)
Referenced by build_stubs_output_lib(), build_stubs_output_lib_new(), gprof_cleanup(), load_exports(), load_file(), load_mapfile(), main(), and output_prx().
FILE* fopen64 (const char * , const char *)
int int int char int fprintf (FILE * pOut, const char * zFormat, ...)
Referenced by add_dword(), add_string(), build_exports(), build_exports_output_extern(), build_exports_output_names(), build_exports_output_nids(), build_stubs_output_lib(), build_stubs_output_lib_new(), calculate_outsize(), dump_exports(), find_pspdev_path(), fixup_imports(), fixup_nidmap(), getopt_long(), load_exports(), load_file(), load_mapfile(), load_sections(), main(), output_prx(), output_shstrtab(), print_help(), print_path(), process_args(), process_relocs(), psp_export_alias(), remove_weak_relocs(), and validate_header().
int fputc (int , FILE *)
Referenced by create_elf().
int fputs (const char * , FILE *)
size_t fread (void * , size_t , size_t , FILE *)
Referenced by load_file(), and main().
FILE* freopen (const char * , const char * , FILE *)
int fscanf (FILE * , const char * , ...)
int fseek (FILE * , long , int)
Referenced by load_file(), and main().
int fseeko64 (FILE * , int64_t , int)
int fsetpos (FILE * , const fpos_t *)
long ftell (FILE *)
Referenced by load_file(), and main().
int64_t ftello64 (FILE *)
size_t fwrite (const void * , size_t , size_t , FILE *)
Referenced by create_elf(), gprof_cleanup(), main(), and output_prx().
int getc (FILE *)
int getchar (void)
char* gets (char *)
int int int char* mprintf (const char * zFormat, ...)
int npmPuts (const char * buf)
int nprintf (const char * format, ...)
void perror (const char *)
int int int char int int printf (const char * format, ...)
Referenced by load_mapfile(), main(), print_path(), and usage().
int putc (int , FILE *)
int int int char int int int int putchar (int)
int puts (const char *)
int remove (const char *)
int rename (const char * , const char *)
void rewind (FILE *)
Referenced by load_file().
int scanf (const char * , ...)
int setbuf (FILE * , char *)
int setvbuf (FILE * , char * , int , size_t)
int sio_printf (const char * format, ...)
int int snprintf (char * str, size_t sz, const char * format, ...)
Referenced by build_stubs_output_lib(), build_stubs_output_lib_new(), internal_do_export(), parse_string(), process_command(), psp_export_alias(), psp_export_end(), psp_export_func_hash(), psp_export_func_nid(), psp_export_start(), psp_export_var_hash(), psp_export_var_nid(), pspDebugKbInit(), pspSdkLoadStartModuleWithArgs(), and validate_number().
int int int sprintf (char * buf, const char * fmt, ...)
int sscanf (const char * , const char * , ...)
FILE* tmpfile (void)
char* tmpnam (char *)
int ungetc (int , FILE *)
int vasprintf (char ** strp, const char * format, va_list ap)
int vfprintf (FILE * pOut, const char * zFormat, va_list ap)
int vfscanf (FILE * , const char * , va_list)
char* vmprintf (const char * zFormat, va_list ap)
int vnprintf (const char * format, va_list args)
int vprintf (const char * format, va_list ap)
int vscanf (const char * , va_list)
int vsnprintf (char * buf, size_t n, const char * fmt, va_list ap)
int vsprintf (char * buf, const char * fmt, va_list ap)
int vsscanf (const char * , const char * , va_list)
int vxprintf (void(*)(char *, int, void *) func, void * arg, const char * format, va_list ap)
int vxscanf (int(*)(void **) xgetc, void(*)(int, void **) xungetc, void * stream, const char * , va_list)
int xprintf (void(*)(char *, int, void *) func, void * arg, const char * format, ...)
int xscanf (int(*)(void **) xgetc, void(*)(int, void **) xungetc, void * stream, const char * , ...)
Variable Documentation
FILE __iob[_NFILE]