pspsdk-1.0+beta2: src/libc/stdlib.h File Reference
stdlib.h File Reference
#include <pspkernel.h>
#include <stddef.h>
Data Structures
struct div_t
struct ldiv_t
struct lldiv_t
Defines
#define NULL (void *)0
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#define MB_CUR_MAX 1
#define __DIV_T_DEFINED
#define __LDIV_T_DEFINED
#define __LLDIV_T_DEFINED
#define RAND_MAX 2147483647
Functions
void abort (void) __attribute__((noreturn))
int abs (int)
int atexit (void(*)(void))
double atof (const char *)
void exit (int)
void * bsearch (const void *, const void *, size_t, size_t, int(*)(const void *, const void *))
div_t div (int, int)
char * getenv (const char *)
long labs (long)
ldiv_t ldiv (long, long)
long long llabs (long long)
lldiv_t lldiv (long long, long long)
int rand (void)
int setenv (const char *, const char *, int)
void srand (unsigned int)
double strtod (const char *, char **)
long strtol (const char *, char **, int)
unsigned long strtoul (const char *, char **, int)
void qsort (void *base, size_t nmemb, size_t size, int(*compar)(const void *, const void *))
int mblen (const char *, size_t)
size_t mbstowcs (wchar_t *, const char *, size_t)
int mbtowc (wchar_t *, const char *, size_t)
size_t wcstombs (char *, const wchar_t *, size_t)
int wctomb (char *, wchar_t)
char * _itoa (int, char *, int)
char * _ltoa (long, char *, int)
char * _lltoa (long long, char *, int)
int system (const char *string)
Define Documentation
#define __DIV_T_DEFINED
#define __LDIV_T_DEFINED
#define __LLDIV_T_DEFINED
#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0
#define MB_CUR_MAX 1
#define NULL (void *)0
#define RAND_MAX 2147483647
Function Documentation
char* _itoa (int , char * , int)
char* _lltoa (long long, char * , int)
char* _ltoa (long , char * , int)
void abort (void)
int abs (int)
int atexit (void(*)(void))
Referenced by _main().
double atof (const char *)
void* bsearch (const void * , const void * , size_t , size_t , int(*)(const void *, const void *))
div_t div (int , int)
void exit (int)
Referenced by _main().
char* getenv (const char *)
Referenced by find_pspdev_path(), and print_path().
long labs (long)
ldiv_t ldiv (long , long)
long long llabs (long long)
lldiv_t lldiv (long long, long long)
int mblen (const char * , size_t)
size_t mbstowcs (wchar_t * , const char * , size_t)
int mbtowc (wchar_t * , const char * , size_t)
void qsort (void * base, size_t nmemb, size_t size, int(*)(const void *, const void *) compar)
int rand (void)
int setenv (const char * , const char * , int)
void srand (unsigned int)
double strtod (const char * , char **)
long strtol (const char * , char ** , int)
unsigned long strtoul (const char * , char ** , int)
Referenced by add_dword(), load_mapfile(), and validate_number().
int system (const char * string)
size_t wcstombs (char * , const wchar_t * , size_t)
int wctomb (char * , wchar_t)