pspsdk-1.0+beta2: src/libc/string.h File Reference
string.h File Reference
#include <stddef.h>
#include <stdarg.h>
#include <ctype.h>
Defines
#define stricmp strcasecmp
#define strnicmp strncasecmp
Functions
void * memchr (const void *, int, size_t)
void * memcpy (void *, const void *, size_t)
void * memmove (void *, const void *, size_t)
void * memset (void *, int, size_t)
int memcmp (const void *, const void *, size_t)
int strcmp (const char *, const char *)
int strncmp (const char *, const char *, size_t)
unsigned int strlen (const char *)
char * strdup (const char *s)
char * strcat (char *, const char *)
char * strchr (const char *, int)
char * strcpy (char *, const char *)
char * strncat (char *, const char *, size_t)
char * strncpy (char *, const char *, size_t)
char * strpbrk (const char *s, const char *accept)
size_t strspn (const char *s, const char *accept)
size_t strcspn (const char *s, const char *reject)
char * strerror (int)
int strcpy_sjis (short *sjis_buff, const char *ascii_buff)
int strcpy_ascii (char *ascii_buff, const short *sjis_buff)
int strcasecmp (const char *, const char *)
int strncasecmp (const char *, const char *, size_t)
char * strtok (char *, const char *)
char * strrchr (const char *, int)
char * strstr (const char *, const char *)
char * strupr (char *)
char * strlwr (char *)
Define Documentation
#define stricmp strcasecmp
#define strnicmp strncasecmp
Function Documentation
void* memchr (const void * , int , size_t)
int memcmp (const void * , const void * , size_t)
void* memcpy (void * , const void * , size_t)
Referenced by main(), output_alloc(), output_relocs(), pspSdkQueryModuleInfoV1(), pspSdkReferCallbackStatusByName(), pspSdkReferEventFlagStatusByName(), pspSdkReferFplStatusByName(), pspSdkReferMboxStatusByName(), pspSdkReferMppStatusByName(), pspSdkReferSemaStatusByName(), pspSdkReferThreadEventHandlerStatusByName(), pspSdkReferThreadStatusByName(), pspSdkReferVplStatusByName(), pspSdkReferVTimerStatusByName(), remove_weak_relocs(), sha1_compile(), and sha1_hash().
void* memmove (void * , const void * , size_t)
Referenced by strip_wsp().
void* memset (void * , int , size_t)
Referenced by add_dword(), add_string(), internal_do_export(), load_mapfile(), load_sections(), main(), output_prx(), output_sh(), output_shstrtab(), psp_export_alias(), psp_export_start(), pspDebugGdbStubInit(), pspDebugGetStackTrace2(), and pspSdkLoadStartModuleWithArgs().
int strcasecmp (const char * , const char *)
char* strcat (char * , const char *)
Referenced by create_elf(), and find_pspdev_path().
char* strchr (const char * , int)
Referenced by add_dword(), add_string(), find_pspdev_path(), getopt_long(), and load_mapfile().
int strcmp (const char * , const char *)
Referenced by build_exports(), build_stubs(), find_alias(), find_map_by_name(), find_name(), find_pspdev_path(), load_sections(), and process_command().
char* strcpy (char * , const char *)
Referenced by create_elf(), find_pspdev_path(), load_sections(), main(), output_shstrtab(), pspAudioInit(), and pspSdkLoadStartModuleWithArgs().
int strcpy_ascii (char * ascii_buff, const short * sjis_buff)
int strcpy_sjis (short * sjis_buff, const char * ascii_buff)
size_t strcspn (const char * s, const char * reject)
char* strdup (const char * s)
char* strerror (int)
unsigned int strlen (const char *)
Referenced by _main(), calculate_outsize(), create_elf(), find_pspdev_path(), getopt_long(), main(), output_sh(), output_shstrtab(), psp_export_func_hash(), psp_export_var_hash(), pspDebugKbDrawKey(), pspDebugKbInit(), pspSdkLoadStartModuleWithArgs(), and strip_wsp().
char* strlwr (char *)
int strncasecmp (const char * , const char * , size_t)
char* strncat (char * , const char * , size_t)
Referenced by find_pspdev_path().
int strncmp (const char * , const char * , size_t)
Referenced by getopt_long(), and main().
char* strncpy (char * , const char * , size_t)
Referenced by find_pspdev_path(), internal_do_export(), load_mapfile(), main(), psp_export_alias(), and psp_export_start().
char* strpbrk (const char * s, const char * accept)
char* strrchr (const char * , int)
size_t strspn (const char * s, const char * accept)
char* strstr (const char * , const char *)
char* strtok (char * , const char *)
Referenced by find_pspdev_path(), and parse_string().
char* strupr (char *)