pspsdk-1.0+beta2: tools/unpack-pbp.c File Reference
unpack-pbp.c File Reference
#include <stdio.h>
#include <stdlib.h>
Data Structures
struct HEADER
Functions
int main (int argc, char *argv[])
Variables
char correct_sig [4]
char * filename [8]
int maxbuffer = 16 * 1024 * 1024
Function Documentation
int main (int argc, char * argv[])
References buffer, correct_sig, fclose(), fopen(), fread(), free(), fseek(), ftell(), fwrite(), header, malloc(), maxbuffer, NULL, HEADER::offset, printf(), SEEK_END, SEEK_SET, HEADER::signature, and size.
Variable Documentation
char correct_sig[4]
Initial value:
 {
   0x00,
   0x50,
   0x42,
   0x50
}
Referenced by main().
char* filename[8]
Initial value:
 {
   "PARAM.SFO",
   "ICON0.PNG",
   "ICON1.PMF",
   "PIC0.PNG",
   "PIC1.PNG",
   "SND0.AT3",
   "DATA.PSP",
   "DATA.PSAR"
}
Referenced by build_stubs_output_lib(), and build_stubs_output_lib_new().
int maxbuffer = 16 * 1024 * 1024